### ISSUE TITLE
IndexError: column index (15100) out of range

### ISSUE THREAD

**Issue by frwjo** [tariks/peakachu#25]
hello Tariks,
I run the code : peakachu train -r 10000 -p maizeB73.allValidPairs_10000.hic.cool -O models -b maizeB73.10kb.bedpe ,  
my  maizeB73.allValidPairs_10000.hic.cool  comes from hicpro'allvalidpairs and convert to .hic and .cool ,and my maizeB73.10kb.bedpe come from hicexplorer :hicConvertFormat -m maizeB73.allValidPairs_10000.hic.cool  --inputFormat cool --outputFormat ginteractions -o maizeB73.allValidPairs.10kb.ginterections.tsv .But I met the problem :
Traceback (most recent call last):
  File "/pub4/wujie/miniconda3/envs/peakachu/bin/peakachu", line 91, in <module>
    run()
  File "/pub4/wujie/miniconda3/envs/peakachu/bin/peakachu", line 87, in run
    args.func(args)
  File "/pub4/wujie/miniconda3/envs/peakachu/lib/python3.10/site-packages/peakachu/train_models.py", line 64, in main
    if X[b1, b2] > maxv:
  File "/pub4/wujie/miniconda3/envs/peakachu/lib/python3.10/site-packages/scipy/sparse/_index.py", line 46, in __getitem__
    row, col = self._validate_indices(key)
  File "/pub4/wujie/miniconda3/envs/peakachu/lib/python3.10/site-packages/scipy/sparse/_index.py", line 163, in _validate_indices
    raise IndexError('column index (%d) out of range' % col)
IndexError: column index (15100) out of range
How to solve the problem?Many thanks.
frwjo

**Comment by frwjo** [comment]
cut -f 1,2,3,4,5,6 maizeB73.allValidPairs.10kb.ginterections.tsv > maizeB73.10kb.bedpe
